### ISSUE TITLE
有去程的吗？

### ISSUE THREAD

**Issue by Rakau** [zhucaidan/mtr_trace#6]
RT

**Comment by zhucaidan** [comment]
https://www.itdog.cn/tracert/

**Comment by Rakau** [comment]
> https://www.itdog.cn/tracert/

我的意思能脚本一样实现。可以嘛

**Comment by zhucaidan** [comment]
https://www.ipip.net/product/client.html
Linux客户端可以的，A到B服务器路由

**Comment by Rakau** [comment]
> https://www.ipip.net/product/client.html Linux客户端可以的，A到B服务器路由

3Q
